---
title: "Data Import Practice"
format: html
editor: visual
---

## Step 1: Read in the dataset `ages.csv`.

```{r}
#| message: false
# Code to read in the ages.csv data goes here! 
ages_csv <- read_csv(here::here("supporting_artifacts", 
                                "Practice_Activities", 
                                "Week2", 
                                "Ages_Data",
                                "ages.csv"))
```

## Step 2: Read in the dataset `ages_tab.txt`

```{r}
#| message: false
# Code to read in the ages_tab.txt data goes here! 
ages_tabs <- read_tsv(here::here("supporting_artifacts", 
                                 "Practice_Activities", 
                                 "Week2", 
                                 "Ages_Data", 
                                 "ages_tab.txt"))
```

## Step 3: Read in the dataset `ages_mystery.txt`

```{r}
# Code to read in the ages_mystery.txt data goes here! 

ages_mystery <- read_delim(here::here("supporting_artifacts", 
                                  "Practice_Activities", 
                                  "Week2", 
                                  "Ages_Data",
                                  "ages_mystery.txt"), 
                       delim = "|", 
                       col_names = TRUE, 
                       show_col_types = FALSE)
```

## Step 4: Read in the dataset `ages.xlsx`

```{r}
# Code to read in the ages.xlsx data goes here! 

ages_xls <- readxl::read_xlsx(here::here("supporting_artifacts",
                                         "Practice_Activities", 
                                         "Week2", 
                                         "Ages_Data", 
                                         "ages.xlsx"),
                              sheet = "ages")
```

## Step 5: Both `read.csv` and `read.table` have an optional argument called `stringsAsFactors`. Figure out what this does.

## Step 6: Find a way to use `read_csv()` to read `ages.csv` with the variable "Name" as a factor and "Age" as a character.

```{r}
# Code to read in the ages.csv with "Name" as a factor and "Age" as a character goes here! 


```

------------------------------------------------------------------------
