---
title: "Lightening Round Essays"
author: Jamie Thompson
format: 
  html: 
    self-contained: true
title-block-banner: true
title-block-banner-color: "light blue"
editor: visual
---

**Lightning round**: Answer each of the following questions with **one sentence** including a brief explanation.

1.  "If \[Student\] doesn't earn an A, then nobody should, because..."

    -   Not sure I like this question. I don't know many students in the class or how they are doing. Also, I think 'grades' especially in this class are not based on a specific individual setting **the** **bar**, but rather how everyone as a single individual evolves through their own learning style and time frame needed.

2.  What was the most difficult part of the class for you? List a general topic, a specific problem, a kind of work we did, etc. and explain why.

    -   Thinking of ways to visualize data from a data set. What graph/graphs best to use to represent the variables you want to show and how to make the visualization look pleasant to the viewer.

3.  What was the easiest part of the class for you? Explain why.

    -   Finding motivation to do the assignments! They were really fun to do and felt very rewarding once completed.

4.  What part of the class surprised or interested you the most? Explain why.

    -   That making the documents would be that fun. Sometimes it was frustrating but after figuring out the issues and finding solutions it was very rewarding. I'd like to use this knowledge and do more statistics based evaluations like we did in week 9.

5.  Give one piece of advice to a student just beginning a quarter of STAT 331 that will help them be successful in learning.

    -   Get use to googling a lot of stuff to help you figure out what you are trying to accomplish!
